export const compressionResponseSchema = {
  name: 'pdf_resume_compression',
  strict: true,
  schema: {
    type: 'object',
    properties: {
      basicInfo: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          title: { type: 'string' },
          phone: { type: 'string' },
          email: { type: 'string' },
          gender: { type: 'string' },
          location: { type: 'string' },
          website: { type: 'string' },
          education: { type: 'string' },
          university: { type: 'string' },
          major: { type: 'string' },
          workYears: { type: 'string' },
          avatarUrl: { type: 'string' },
        },
        required: [
          'name',
          'title',
          'phone',
          'email',
          'gender',
          'location',
          'website',
          'education',
          'university',
          'major',
          'workYears',
          'avatarUrl',
        ],
        additionalProperties: false,
      },
      skills: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            name: { type: 'string' },
            description: { type: 'string' },
          },
          required: ['id', 'name', 'description'],
          additionalProperties: false,
        },
      },
      experience: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            company: { type: 'string' },
            position: { type: 'string' },
            startDate: { type: 'string' },
            endDate: { type: 'string' },
            highlights: {
              type: 'array',
              items: { type: 'string' },
            },
          },
          required: [
            'id',
            'company',
            'position',
            'startDate',
            'endDate',
            'highlights',
          ],
          additionalProperties: false,
        },
      },
      projects: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            name: { type: 'string' },
            role: { type: 'string' },
            startDate: { type: 'string' },
            endDate: { type: 'string' },
            description: { type: 'string' },
            highlights: {
              type: 'array',
              items: { type: 'string' },
            },
          },
          required: [
            'id',
            'name',
            'role',
            'startDate',
            'endDate',
            'description',
            'highlights',
          ],
          additionalProperties: false,
        },
      },
      education: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            school: { type: 'string' },
            degree: { type: 'string' },
            major: { type: 'string' },
            startDate: { type: 'string' },
            endDate: { type: 'string' },
            description: { type: 'string' },
          },
          required: [
            'id',
            'school',
            'degree',
            'major',
            'startDate',
            'endDate',
            'description',
          ],
          additionalProperties: false,
        },
      },
    },
    required: ['basicInfo', 'skills', 'experience', 'projects', 'education'],
    additionalProperties: false,
  },
} as const
