export const compressionResponseSchema = {
  name: 'pdf_resume_compression',
  strict: true,
  schema: {
    type: 'object',
    properties: {
      basicInfo: {
        type: 'object',
        properties: {
          name: { type: 'string' },
          gender: { type: 'string' },
          age: { type: 'string' },
          phone: { type: 'string' },
          email: { type: 'string' },
          education: { type: 'string' },
          university: { type: 'string' },
          major: { type: 'string' },
          workYears: { type: 'string' },
          jobTarget: { type: 'string' },
          website: { type: 'string' },
        },
        required: [
          'name',
          'gender',
          'age',
          'phone',
          'email',
          'education',
          'university',
          'major',
          'workYears',
          'jobTarget',
          'website',
        ],
        additionalProperties: false,
      },
      strengths: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            content: { type: 'string' },
          },
          required: ['id', 'content'],
          additionalProperties: false,
        },
      },
      workExperience: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            company: { type: 'string' },
            title: { type: 'string' },
            startDate: { type: 'string' },
            endDate: { type: 'string' },
            content: { type: 'string' },
          },
          required: ['id', 'company', 'title', 'startDate', 'endDate', 'content'],
          additionalProperties: false,
        },
      },
      projectExperience: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            name: { type: 'string' },
            tag: { type: 'string' },
            startDate: { type: 'string' },
            endDate: { type: 'string' },
            background: { type: 'string' },
            responsibilities: { type: 'string' },
            results: { type: 'string' },
          },
          required: [
            'id',
            'name',
            'tag',
            'startDate',
            'endDate',
            'background',
            'responsibilities',
            'results',
          ],
          additionalProperties: false,
        },
      },
    },
    required: ['basicInfo', 'strengths', 'workExperience', 'projectExperience'],
    additionalProperties: false,
  },
} as const
